image: ubuntu:22.04

before_script:
  - apt update
  - apt install -y g++ make libgtest-dev cmake
  - export REPO_DIR=$(pwd)
  - cd /usr/src/gtest
  - cmake CMakeLists.txt
  - make
  - cd lib
  - cp *.a /usr/lib
  - cd $REPO_DIR

stages:
  - test
  - analysis

Run test with GoogleTest:
  stage: test
  script:
    - make

Check memory leak with Valgrind:
  stage: analysis
  script:
    - apt install -y valgrind
    - make valgrind
