include:
  template: Security/SAST.gitlab-ci.yml

image: ubuntu:22.04

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y g++ make libgtest-dev cmake
    - cd /usr/src/gtest
    - cmake CMakeLists.txt
    - make
    - cd lib
    - cp *.a /usr/lib
  script:
    - cd /builds/108820026/posd2022f_108820026_hw
    - make
  artifacts:
    paths:
      - bin

# run tests using the binary built before
test:
  stage: test
  script:
    - bin/ut_all
