name: test coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Test coverage
    steps:
    - name: Install gtest manually
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Install Python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install gcovr for xml coverage report
      run: |
        python -m pip install --upgrade pip
        pip install gcovr
    - name: Run tests and collect coverage
      run: make coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
