name: test coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Test coverage
    steps:
    - name: Install gtest manually
      run: |
        sudo apt-get update
        sudo apt-get install g++
        sudo apt-get install make
        sudo apt-get install libgtest-dev
        sudo apt-get install cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        cd lib
        sudo cp *.a /usr/lib
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install gcovr for xml coverage report
      run: |
        python -m pip install --upgrade pip
        pip install gcovr
    - name: Run tests and collect coverage
      run: make coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
